#!/bin/bash

if [ $# -ne 0 ]; then  # script does not take arguments
    echo "ERROR: invalid argument given"
    exit 1
else
    # cut by ':' and select only characters at the left of it
    # sort -u to remove duplicates
    echo $(groups `users` | grep ugrad | cut -d: -f1 | sort -u)
fi
