#!/bin/bash

org_arg="$@"  # save original arguments
has_arg=""
col=5         # default colon to sort
rev='-r'      # default sort reverse
TEMP=$(getopt -o ':fgiorsxCR' -l 'reverse,recursive,size' -- "$@")
eval set -- "$TEMP"
unset TEMP

while true; do
    case "$1" in
        '-C'|'-R'|'-x'|'--recursive')
            echo "ERROR: invalid option"
            exit 1
        ;;
        '-r'|'--reverse')
            rev=''
            shift
        ;;
        '-i'|'-s'|'--size')
            col=6
            shift
        ;;
        '-g'|'-G'|'-o')
            col=4
            shift
        ;;
        '--')
            shift
            break
        ;;
    esac
done

# if there is remaining arguments, add option -d
for arg; do
    has_arg="-d"
    break
done

ls -l $has_arg $org_arg | sort $rev -gk $col
