#!/bin/bash

# we will use awk to generate another awk script, which combines column names
# and the user input code, then execute the generated script

# $1: user input script
# $2: tsv file

# beginning of awk code that need to be generated
start='BEGIN{ finish = 0 }
/^#/ {next}
finish == 0 {
    finish = 1   # skips the first non-comment line (header)
    next
}'

generated=$(
cat $2 | gawk -F"\t" -v script="$1" -v start="$start" '
BEGIN{ print start }                    # prints the beginning
/^#/ {next}                             # ignore comment
{
    printf "{"
    for(i = 1; i <= NF; ++i) {
        printf "%s=$%s\n", $i, i        # assign column to header name
    }
    printf "}" 
    exit                                # only need to process header here
}
END{ print script }                     # append user input
')

# execute generated awk script
cat $2 | gawk "$generated"
